// errors.h
//
// This module contains error codes for all type and scope errors which arise
// when parsing UnCool code.

#define DUPLICATE_CLASS -1
#define DUPLICATE_ATTRIBUTE -2
#define DUPLICATE_METHOD -3
#define NO_MAIN_CLASS -4
#define NO_MAIN_METHOD -5
#define METHOD_DECL_OUTSIDE_CLASS_SCOPE -6
#define ATTRIBUTE_DECL_IN_GLOBAL_SCOPE -7
#define CLASS_DECL_INSIDE_CLASS_DECL -8
#define NO_SUCH_CLASS -9

#define NO_SUCH_ATTRIBUTE -10
#define NO_SUCH_METHOD -11
#define METHOD_BODY_HAS_CONFLICTING_TYPE -12
#define CONDITIONAL_BRANCH_TYPES_DIFFER -13
#define PREDICATE_NOT_BOOL -14
#define INDEX_NOT_INT -15
#define ARRAY_SIZE_NOT_INT -16
#define CONFLICTING_ATTRIBUTE_TYPE -18
#define METHOD_DECL_INSIDE_METHOD_DECL -19
#define METHOD_INVALID_ARGCOUNT -20
#define INDEXING_NON_ARRAY -21
#define SELF_REFERENCE_OUTSIDE_CLASS -22
#define OUT_INT_EXPECTS_INT -23
#define OBJECT_INSTANTIATION_INVALID_ARGCOUNT -24
#define ARITHMETIC_OP_TYPE_MISMATCH -25
#define COMPARISON_OP_TYPE_MISMATCH -26
#define UNIMINUS_EXPR_NOT_INT -27
#define NOT_EXPR_NOT_BOOL -28
#define COMPARISON_OP_TYPES_NOT_INT -29
#define EXPECTED_INT_OPERANDS -30
#define OUT_STRING_EXPECTS_STRING -31

#define OUT_OF_MEMORY -128
#define CLOBBERING_TYPE -129
